### ISSUE TITLE
Regex vaildater

### ISSUE THREAD

**Issue by NoMoreViolence** [marblejs/marble#118] opened 2019-04-27 04:29 UTC
**Is your feature request related to a problem? Please describe.**
About @marblejs/middleware-io,
I want validate with regex

Now, I validate which using requestValidator (type),
But I have to validate with other pipe function (regexp)

**Describe the solution you'd like**
Add option to validate body parameter with regex

**Describe alternatives you've considered**
```typescript
import { requestValidator$, t } from '@marblejs/middleware-io'

const registerVaildater$ = requestValidator$({
  body: t.type({
    email: t.regex(new Regexp(something)),
    name:  t.regex(new Regexp(something)),
    password:  t.regex(new Regexp(something)),
    rPassword:  t.regex(new Regexp(something))
  })
});
```

**Additional context**

**Comment by NoMoreViolence** [comment] 2019-04-27 04:36
I can try to make this feature If you want.

**Comment by krzysztof-miemiec** [comment] 2019-04-27 08:18
As stated in [the docs for `middleware-io`](https://docs.marblejs.com/api-reference-2/middleware-io), the middleware is based on `io-ts` library. You can use https://gcanti.github.io/io-ts-types/modules/regexp.ts.html from `io-ts-types` which should allow you to do something like:
```ts
import { requestValidator$, t } from '@marblejs/middleware-io';
import { regexp } from 'io-ts-types';

const registerVaildator$ = requestValidator$({
  body: t.type({
    email: regexp(new Regexp(something)),
    name:  regexp(new Regexp(something)),
    password:  regexp(new Regexp(something)),
    rPassword:  regexp(new Regexp(something))
  })
});
```

**Comment by NoMoreViolence** [comment] 2019-04-27 08:33
Oh, I didn't know that, Thanks

**Comment by NoMoreViolence** [comment] 2019-04-27 08:55
@krzysztof-miemiec Your example not works right now

There is an error
```
Cannot invoke an expression whose type lacks a call signature. 
Type 'RegExpC' has no compatible call signatures.ts(2349)
```

```typescript
import { email as emailRegex, password } from '@lib/regex';
import { requestValidator$, t } from '@marblejs/middleware-io';
import { regexp } from 'io-ts-types/lib/regexp';

const loginVaildater$ = requestValidator$({
  body: t.type({
    email: regexp(emailRegex),
    password: t.string
  })
});
```

**Comment by JozefFlakus** [comment] 2019-04-27 09:19
Hi @NoMoreViolence,

The issue is connected to `io-ts` library rather than `@marblejs/middleware-io` itself.
I'm not sure if the `io-ts-types` lib is fully compatible with the latest version of `io-ts`. Maybe it is a bug that should be reported to the author? 🤔 

Anyway, I would try to build your own custom codec (type), as stated in [docs](https://github.com/gcanti/io-ts#custom-types).

**Comment by JozefFlakus** [comment] 2019-04-28 15:18
Closing this issue because it is not related to `@marblejs/middleware-io` package.

**Closed by JozefFlakus** 2019-04-28 15:18 UTC
Labels: help wanted, scope: middleware
