### ISSUE TITLE
Cannot find module 'rxjs/internal/scheduler/AsyncScheduler' from 'node_modules/@marblejs/core/dist/effects/effectsContext.factory.js' when running jest

### ISSUE THREAD

**Issue by alvarorodriguezestruch** [marblejs/marble#339] opened 2021-07-02 15:29 UTC
**Describe the bug**
Im triying to create some test to a project with jest and im using marblejs for building the server.
The point is that there is no problem when im running the code, but when I try to execute any file with jest which require the `@marblejs/core` module or any file that internally imports it, its returns the following error:

```
Cannot find module 'rxjs/internal/scheduler/AsyncScheduler' from 'node_modules/@marblejs/core/dist/effects/effectsContext.factory.js'

    Require stack:
      node_modules/@marblejs/core/dist/effects/effectsContext.factory.js
      node_modules/@marblejs/core/dist/http/server/http.server.js
      node_modules/@marblejs/core/dist/index.js
      utils.helper.js
      utiles.test.js
```

Im not sure if this is a marblejs bug or maybe a jest bug, but i will appreciate any help to discover it.

**To Reproduce**
I have create a stackblitx for it, just run `jest ` command
https://stackblitz.com/edit/node-sbtfbd?file=utils.test.js

**Expected behavior**
The test fails because my own mistake :)

**Desktop (please complete the following information):**
 - Windows 10
 - MarbleJS:  3.5.0
 - Jest: 27.0.6
 - Node:  14.17.1

**Comment by JozefFlakus** [comment] 2021-07-02 15:41
@marblejs v3.5 is not compatible with latest RxJS v7. Closing due to a duplicate of: https://github.com/marblejs/marble/issues/324

**Closed by JozefFlakus** 2021-07-02 15:41 UTC
Labels: duplicate

**Comment by JozefFlakus** [comment] 2021-07-02 15:42
Marble.js v4 with a support with RxJS v7 will be released soon. :)

**Comment by alvarorodriguezestruch** [comment] 2021-07-02 16:01
downgrading rxjs to 6.6.7 until v4 get released, solves the problem.

thanks for quick response! :)
